import { z } from 'zod';
import { sendTelegramMessage, TelegramUpdate } from './telegram';
import { createJiraIssue, JiraToolAuth } from './tools/jira';

export type EnvName = 'dev'|'stage'|'prod';
export type Severity = 'info'|'warning'|'error'|'critical';
export interface OpsEnv { ENVIRONMENT?: string; AGENTIC_ADMIN_TOKEN?: string; TELEGRAM_BOT_TOKEN?: string; TELEGRAM_WEBHOOK_SECRET?: string; TELEGRAM_ADMIN_CHAT_IDS?: string; TELEGRAM_ALLOWED_USER_IDS?: string; TELEGRAM_CHAT_ID?: string; ATLASSIAN_BASE_URL?: string; ATLASSIAN_EMAIL?: string; ATLASSIAN_API_TOKEN?: string; JIRA_BASE_URL?: string; JIRA_USER_EMAIL?: string; JIRA_API_TOKEN?: string; JIRA_PROJECT_KEY?: string; AI_MODEL?: string; INCIDENT_NOTIFICATION_THRESHOLDS?: string; INCIDENT_REOPEN_COOLDOWN_MINUTES?: string; APPROVAL_EXPIRATION_MINUTES?: string; HEALTH_CHECK_TIMEOUT_MS?: string; AGENT_ENABLED?: string; INTERNAL_STATUS_SECRET?: string; AGENT_DB: D1Database; AI_AUDIT_BUCKET?: R2Bucket; }
export interface AgentTask { id:string; type:string; source:'schedule'|'telegram'|'event'|'system'; status:'pending'|'running'|'waiting_for_approval'|'completed'|'failed'|'cancelled'; priority:'low'|'normal'|'high'|'critical'; input:Record<string,unknown>; result?:Record<string,unknown>; error?:{code?:string;message:string;retryable:boolean}; createdAt:string; startedAt?:string; completedAt?:string; correlationId:string; }
export interface SystemObservation { id:string; source:'health_endpoint'|'workflow'|'queue'|'worker_log'|'database'|'ai_gateway'|'manual'; category:'availability'|'workflow_failure'|'queue_backlog'|'database_error'|'ai_generation_error'|'performance'|'cost'|'unknown'; severity:Severity; service:string; environment:EnvName; timestamp:string; summary:string; fingerprint:string; metadata:Record<string,unknown>; }
export interface IncidentDiagnosis { probableCause:string; confidence:'low'|'medium'|'high'; evidence:string[]; recommendedActions:Array<{action:string;risk:'low'|'medium'|'high';requiresApproval:boolean}>; jiraTitle:string; jiraDescription:string; }
export interface Incident { id:string; fingerprint:string; title:string; service:string; environment:EnvName; severity:Exclude<Severity,'info'>; status:'open'|'acknowledged'|'jira_pending'|'jira_created'|'resolved'|'ignored'; occurrenceCount:number; firstSeenAt:string; lastSeenAt:string; latestObservationId:string; diagnosis?:IncidentDiagnosis; jiraIssueKey?:string; telegramMessageId?:string; lastNotifiedAt?:string; }
export interface ApprovalRequest { id:string; token:string; action:'create_jira_issue'; resourceType:'incident'; resourceId:string; status:'pending'|'approved'|'rejected'|'expired'|'executed'; requestedAt:string; expiresAt:string; decidedAt?:string; decidedBy?:string; executionResult?:Record<string,unknown>; }
export interface AgentRuntimeState { paused:boolean; pausedAt?:string; pausedBy?:string; pauseReason?:string; lastScheduledRunAt?:string; lastSuccessfulRunAt?:string; lastFailedRunAt?:string; }

const diagSchema = z.object({ probableCause:z.string(), confidence:z.enum(['low','medium','high']), evidence:z.array(z.string()), recommendedActions:z.array(z.object({action:z.string(),risk:z.enum(['low','medium','high']),requiresApproval:z.boolean()})), jiraTitle:z.string(), jiraDescription:z.string() });
export const toolPolicies = [
  'getSystemHealth','getRecentWorkflowFailures','getQueueBacklog','getRecentApplicationErrors','getRecentAiGenerationFailures'
].map(name=>({name,riskLevel:'read',allowedEnvironments:['dev','stage','prod'],requiresApproval:false,idempotent:true,maxCallsPerRun:1,timeoutMs:8000}));
export const createJiraPolicy={name:'createJiraIssue',riskLevel:'medium',allowedEnvironments:['dev','stage'],requiresApproval:true,idempotent:true,maxCallsPerRun:1,timeoutMs:10000};
export function id(prefix:string){return `${prefix}_${crypto.randomUUID().replace(/-/g,'').slice(0,24)}`}
export function envName(v?:string):EnvName{return v==='production'||v==='prod'?'prod':v==='stage'?'stage':'dev'}
export function normalizeForFingerprint(s:string){return s.toLowerCase().replace(/\brequest [a-z0-9]+\b/gi,'<request>').replace(/[0-9a-f]{8}-[0-9a-f-]{27,}/gi,'<uuid>').replace(/\b(req|request|corr|correlation)[-_ ]?[a-z0-9]+\b/gi,'<request>').replace(/\b(request|correlation) [a-z0-9]+\b/gi,'<request>').replace(/\b\d{4}-\d{2}-\d{2}[t ][^\s]+/gi,'<timestamp>').replace(/\b\d+ms\b/gi,'<duration>').replace(/:\d+:\d+/g,':<line>').replace(/\b\d{5,}\b/g,'<num>').replace(/\s+/g,' ').trim()}
async function sha(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,32)}
export async function fingerprintObservation(o:Omit<SystemObservation,'id'|'fingerprint'|'timestamp'>){return sha([o.source,o.category,o.severity,o.service,o.environment,normalizeForFingerprint(o.summary)].join('|'))}
export function redact(value:unknown):unknown{if(Array.isArray(value))return value.map(redact); if(value&&typeof value==='object'){const out:Record<string,unknown>={}; for(const [k,v] of Object.entries(value)){out[k]=/(authorization|api.?key|cookie|token|secret|password|email|source.?code|prompt)/i.test(k)?'[redacted]':redact(v)} return out} if(typeof value==='string')return value.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[redacted-email]'); return value}
export async function ensureOpsSchema(db:D1Database){await db.exec(`CREATE TABLE IF NOT EXISTS agent_tasks(id TEXT PRIMARY KEY,type TEXT,source TEXT,status TEXT,priority TEXT,input TEXT,result TEXT,error TEXT,created_at TEXT,started_at TEXT,completed_at TEXT,correlation_id TEXT);CREATE INDEX IF NOT EXISTS idx_agent_tasks_status_created ON agent_tasks(status,created_at);
CREATE TABLE IF NOT EXISTS system_observations(id TEXT PRIMARY KEY,source TEXT,category TEXT,severity TEXT,service TEXT,environment TEXT,timestamp TEXT,summary TEXT,fingerprint TEXT,metadata TEXT,task_id TEXT, UNIQUE(fingerprint,timestamp,summary));CREATE INDEX IF NOT EXISTS idx_obs_fp ON system_observations(fingerprint);
CREATE TABLE IF NOT EXISTS incidents(id TEXT PRIMARY KEY,fingerprint TEXT,title TEXT,service TEXT,environment TEXT,severity TEXT,status TEXT,occurrence_count INTEGER,first_seen_at TEXT,last_seen_at TEXT,latest_observation_id TEXT,diagnosis TEXT,jira_issue_key TEXT,telegram_message_id TEXT,last_notified_at TEXT);CREATE INDEX IF NOT EXISTS idx_inc_fp ON incidents(fingerprint);CREATE INDEX IF NOT EXISTS idx_inc_status_sev ON incidents(status,severity);
CREATE TABLE IF NOT EXISTS approval_requests(id TEXT PRIMARY KEY,token TEXT UNIQUE,action TEXT,resource_type TEXT,resource_id TEXT,status TEXT,requested_at TEXT,expires_at TEXT,decided_at TEXT,decided_by TEXT,execution_result TEXT);CREATE INDEX IF NOT EXISTS idx_approval_token_status ON approval_requests(token,status);
CREATE TABLE IF NOT EXISTS audit_events(id TEXT PRIMARY KEY,correlation_id TEXT,event_type TEXT,actor TEXT,resource_type TEXT,resource_id TEXT,timestamp TEXT,environment TEXT,outcome TEXT,metadata TEXT,r2_key TEXT);CREATE INDEX IF NOT EXISTS idx_audit_corr_ts ON audit_events(correlation_id,timestamp);
CREATE TABLE IF NOT EXISTS runtime_state(id TEXT PRIMARY KEY,paused INTEGER,paused_at TEXT,paused_by TEXT,pause_reason TEXT,last_scheduled_run_at TEXT,last_successful_run_at TEXT,last_failed_run_at TEXT);`)}
async function audit(env:OpsEnv,e:any){const safe=redact(e.metadata??{}); await env.AGENT_DB.prepare('INSERT INTO audit_events VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11)').bind(id('aud'),e.correlationId,e.eventType,e.actor,e.resourceType??null,e.resourceId??null,new Date().toISOString(),envName(env.ENVIRONMENT),e.outcome,JSON.stringify(safe),e.r2Key??null).run()}
export async function getState(env:OpsEnv):Promise<AgentRuntimeState>{const r=await env.AGENT_DB.prepare('SELECT * FROM runtime_state WHERE id="global"').first<any>(); return r?{paused:!!r.paused,pausedAt:r.paused_at,pausedBy:r.paused_by,pauseReason:r.pause_reason,lastScheduledRunAt:r.last_scheduled_run_at,lastSuccessfulRunAt:r.last_successful_run_at,lastFailedRunAt:r.last_failed_run_at}:{paused:env.AGENT_ENABLED==='false'}}
export async function setPaused(env:OpsEnv,paused:boolean,by:string,reason='telegram command'){const now=new Date().toISOString(); await env.AGENT_DB.prepare('INSERT OR REPLACE INTO runtime_state VALUES("global",?1,?2,?3,?4,(SELECT last_scheduled_run_at FROM runtime_state WHERE id="global"),(SELECT last_successful_run_at FROM runtime_state WHERE id="global"),(SELECT last_failed_run_at FROM runtime_state WHERE id="global"))').bind(paused?1:0,paused?now:null,by,paused?reason:null).run()}
async function putTask(env:OpsEnv,t:AgentTask){await env.AGENT_DB.prepare('INSERT OR REPLACE INTO agent_tasks VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12)').bind(t.id,t.type,t.source,t.status,t.priority,JSON.stringify(t.input),JSON.stringify(t.result??null),JSON.stringify(t.error??null),t.createdAt,t.startedAt??null,t.completedAt??null,t.correlationId).run()}
async function collect(env:OpsEnv):Promise<SystemObservation[]>{const now=new Date().toISOString(); const base=[{source:'health_endpoint',category:'availability',severity:'info',service:'orchestrator',summary:'Worker health endpoint is reachable',metadata:{}},{source:'workflow',category:'workflow_failure',severity:'error',service:'lesson-generation',summary:'Mock recurring lesson generation failed because course mapping could not be resolved for subscription id 123456 in 42ms',metadata:{adapter:'mock',connectLater:'Cloudflare Workflow analytics or app endpoint'}},{source:'queue',category:'queue_backlog',severity:'info',service:'operations-queue',summary:'No queue backlog adapter configured',metadata:{adapter:'placeholder'}},{source:'worker_log',category:'unknown',severity:'info',service:'worker',summary:'No application error log adapter configured',metadata:{adapter:'placeholder'}},{source:'ai_gateway',category:'ai_generation_error',severity:'info',service:'ai-gateway',summary:'No AI generation failures adapter configured',metadata:{adapter:'placeholder'}}] as any[]; const out:SystemObservation[]=[]; for(const b of base){const fp=await fingerprintObservation({...b,environment:envName(env.ENVIRONMENT)}); out.push({id:id('obs'),timestamp:now,environment:envName(env.ENVIRONMENT),fingerprint:fp,...b});} return out}
function sevRank(s:string){return {info:0,warning:1,error:2,critical:3}[s]??0}
function fallbackDiagnosis(i:Incident,o:SystemObservation[]):IncidentDiagnosis{return{probableCause:`${i.service} reported recurring ${i.severity} observations grouped by fingerprint ${i.fingerprint}.`,confidence:'medium',evidence:o.map(x=>x.summary).slice(0,5),recommendedActions:[{action:'Create a Jira issue for investigation.',risk:'medium',requiresApproval:true}],jiraTitle:`${i.service}: ${i.title}`.slice(0,120),jiraDescription:`Incident ${i.id}\nService: ${i.service}\nEnvironment: ${i.environment}\nOccurrences: ${i.occurrenceCount}\nEvidence:\n${o.map(x=>`- ${x.summary}`).join('\n')}`}}
async function diagnose(env:OpsEnv,i:Incident,o:SystemObservation[],corr:string){let d=fallbackDiagnosis(i,o); const payload={instructions:'Do not invent evidence. Distinguish facts from hypotheses. Use only supplied observations. Do not expose secrets or PII. Flag destructive actions high risk. Keep Jira concise.',incident:i,observations:o.map(x=>({summary:x.summary,severity:x.severity,metadata:redact(x.metadata)}))}; try{await env.AI_AUDIT_BUCKET?.put(`ai/${corr}/${i.id}.json`,JSON.stringify(redact({request:payload,response:d,model:env.AI_MODEL??'deterministic-fallback'}))); const parsed=diagSchema.safeParse(d); if(parsed.success)d=parsed.data;}catch{} return d}
function shouldNotify(i:Incident, old?:Incident){if(!old||!i.telegramMessageId)return true; if(sevRank(i.severity)>sevRank(old.severity))return true; const thresholds=(globalThis as any).__OPS_THRESHOLDS as number[]||[1,3,7,15]; return thresholds.includes(i.occurrenceCount)}
async function aggregate(env:OpsEnv, obs:SystemObservation[], taskId:string, corr:string){const incidents:Incident[]=[]; for(const o of obs.filter(x=>sevRank(x.severity)>=1)){await env.AGENT_DB.prepare('INSERT OR IGNORE INTO system_observations VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11)').bind(o.id,o.source,o.category,o.severity,o.service,o.environment,o.timestamp,o.summary,o.fingerprint,JSON.stringify(o.metadata),taskId).run(); const old=await env.AGENT_DB.prepare('SELECT * FROM incidents WHERE fingerprint=?1 ORDER BY last_seen_at DESC LIMIT 1').bind(o.fingerprint).first<any>(); let inc:Incident; if(old&&['open','acknowledged','jira_pending','jira_created'].includes(old.status)){inc={id:old.id,fingerprint:old.fingerprint,title:old.title,service:old.service,environment:old.environment,severity:sevRank(o.severity)>sevRank(old.severity)?o.severity as any:old.severity,status:old.status,occurrenceCount:old.occurrence_count+1,firstSeenAt:old.first_seen_at,lastSeenAt:o.timestamp,latestObservationId:o.id,diagnosis:old.diagnosis?JSON.parse(old.diagnosis):undefined,jiraIssueKey:old.jira_issue_key,telegramMessageId:old.telegram_message_id,lastNotifiedAt:old.last_notified_at};} else {inc={id:id('inc'),fingerprint:o.fingerprint,title:o.summary.slice(0,100),service:o.service,environment:o.environment,severity:o.severity as any,status:'open',occurrenceCount:1,firstSeenAt:o.timestamp,lastSeenAt:o.timestamp,latestObservationId:o.id};}
    inc.diagnosis=await diagnose(env,inc,[o],corr); await env.AGENT_DB.prepare('INSERT OR REPLACE INTO incidents VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15)').bind(inc.id,inc.fingerprint,inc.title,inc.service,inc.environment,inc.severity,inc.status,inc.occurrenceCount,inc.firstSeenAt,inc.lastSeenAt,inc.latestObservationId,JSON.stringify(inc.diagnosis),inc.jiraIssueKey??null,inc.telegramMessageId??null,inc.lastNotifiedAt??null).run(); incidents.push(inc); }
 return incidents}
async function approval(env:OpsEnv,incidentId:string){const now=Date.now(), minutes=Number(env.APPROVAL_EXPIRATION_MINUTES??'60'); const a={id:id('apr'),token:id('tok'),action:'create_jira_issue',resourceType:'incident',resourceId:incidentId,status:'pending',requestedAt:new Date(now).toISOString(),expiresAt:new Date(now+minutes*60000).toISOString()} as ApprovalRequest; await env.AGENT_DB.prepare('INSERT INTO approval_requests VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11)').bind(a.id,a.token,a.action,a.resourceType,a.resourceId,a.status,a.requestedAt,a.expiresAt,null,null,null).run(); return a}
export function formatIncident(i:Incident,a?:ApprovalRequest){return `🚨 BiteCode incident detected\n\nService: ${i.service}\nEnvironment: ${i.environment}\nSeverity: ${i.severity}\nOccurrences: ${i.occurrenceCount}\nFirst seen: ${i.firstSeenAt}\nLast seen: ${i.lastSeenAt}\n\nSummary:\n${i.title}\n\nProbable cause:\n${i.diagnosis?.probableCause}\n\nRecommended next step:\nCreate a Jira issue for investigation.\n\nApproval ID:\n${a?.token??'none'}`}
export async function runHealthCheck(env:OpsEnv,source:AgentTask['source']='system'){await ensureOpsSchema(env.AGENT_DB); const corr=id('corr'), task:AgentTask={id:id('task'),type:'health_check',source,status:'running',priority:'normal',input:{},createdAt:new Date().toISOString(),startedAt:new Date().toISOString(),correlationId:corr}; await putTask(env,task); await audit(env,{correlationId:corr,eventType:'health_check',actor:'orchestrator',resourceType:'task',resourceId:task.id,outcome:'started'}); try{const obs=await collect(env); const incidents=await aggregate(env,obs,task.id,corr); for(const i of incidents){if(!i.telegramMessageId&&env.TELEGRAM_BOT_TOKEN&&(env.TELEGRAM_CHAT_ID||env.TELEGRAM_ADMIN_CHAT_IDS)){const a=await approval(env,i.id); const chat=Number(env.TELEGRAM_CHAT_ID??env.TELEGRAM_ADMIN_CHAT_IDS?.split(',')[0]); const r=await sendTelegramMessage(env.TELEGRAM_BOT_TOKEN,chat,formatIncident(i,a)); let msg; try{msg=(await r.json() as any)?.result?.message_id?.toString()}catch{} await env.AGENT_DB.prepare('UPDATE incidents SET status="jira_pending", telegram_message_id=?1,last_notified_at=?2 WHERE id=?3').bind(msg??'sent',new Date().toISOString(),i.id).run();}}
 task.status='completed'; task.result={observations:obs.length,incidents:incidents.length}; task.completedAt=new Date().toISOString(); await putTask(env,task); await env.AGENT_DB.prepare('INSERT OR REPLACE INTO runtime_state(id,paused,last_successful_run_at) VALUES("global",COALESCE((SELECT paused FROM runtime_state WHERE id="global"),0),?1)').bind(task.completedAt).run(); await audit(env,{correlationId:corr,eventType:'health_check',actor:'orchestrator',resourceType:'task',resourceId:task.id,outcome:'succeeded',metadata:task.result}); return task;}catch(e){task.status='failed'; task.error={message:e instanceof Error?e.message:'unknown',retryable:true}; task.completedAt=new Date().toISOString(); await putTask(env,task); await audit(env,{correlationId:corr,eventType:'health_check',actor:'orchestrator',resourceType:'task',resourceId:task.id,outcome:'failed',metadata:{error:task.error}}); return task;}}
export async function handleApproval(env:OpsEnv,token:string,decision:'approve'|'reject',by:string){const a=await env.AGENT_DB.prepare('SELECT * FROM approval_requests WHERE token=?1').bind(token).first<any>(); if(!a)return {ok:false,error:'approval_not_found'}; if(a.status==='executed'||a.status==='rejected')return {ok:true,status:a.status,idempotent:true}; if(new Date(a.expires_at).getTime()<Date.now()){await env.AGENT_DB.prepare('UPDATE approval_requests SET status="expired" WHERE token=?1').bind(token).run(); return {ok:false,error:'approval_expired'};} if(decision==='reject'){await env.AGENT_DB.prepare('UPDATE approval_requests SET status="rejected",decided_at=?1,decided_by=?2 WHERE token=?3').bind(new Date().toISOString(),by,token).run(); return {ok:true,status:'rejected'};} const inc=await env.AGENT_DB.prepare('SELECT * FROM incidents WHERE id=?1').bind(a.resource_id).first<any>(); if(!inc)return {ok:false,error:'incident_not_found'}; if(inc.jira_issue_key)return {ok:true,status:'executed',jiraIssueKey:inc.jira_issue_key,idempotent:true}; const auth:JiraToolAuth={baseUrl:env.JIRA_BASE_URL??env.ATLASSIAN_BASE_URL??'',email:env.JIRA_USER_EMAIL??env.ATLASSIAN_EMAIL??'',apiToken:env.JIRA_API_TOKEN??env.ATLASSIAN_API_TOKEN??'',projectKey:env.JIRA_PROJECT_KEY??''}; const diagnosis=inc.diagnosis?JSON.parse(inc.diagnosis):fallbackDiagnosis({id:inc.id,fingerprint:inc.fingerprint,title:inc.title,service:inc.service,environment:inc.environment,severity:inc.severity,status:inc.status,occurrenceCount:inc.occurrence_count,firstSeenAt:inc.first_seen_at,lastSeenAt:inc.last_seen_at,latestObservationId:inc.latest_observation_id},[]); const result=await createJiraIssue(auth,{title:diagnosis.jiraTitle,description:diagnosis.jiraDescription,labels:['bitecode-ops-agent','incident',inc.environment],idempotencyKey:inc.id}); await env.AGENT_DB.prepare('UPDATE incidents SET status="jira_created", jira_issue_key=?1 WHERE id=?2').bind(result.key,inc.id).run(); await env.AGENT_DB.prepare('UPDATE approval_requests SET status="executed",decided_at=?1,decided_by=?2,execution_result=?3 WHERE token=?4').bind(new Date().toISOString(),by,JSON.stringify(result),token).run(); return {ok:true,status:'executed',jiraIssueKey:result.key};}
export function allowedTelegram(env:OpsEnv,userId?:number){const ids=(env.TELEGRAM_ALLOWED_USER_IDS??env.TELEGRAM_ADMIN_CHAT_IDS??'').split(',').map(x=>x.trim()).filter(Boolean); return !!userId&&ids.includes(String(userId))}
export async function handleOpsTelegram(request:Request,env:OpsEnv){const secret=request.headers.get('x-telegram-bot-api-secret-token'); if(env.TELEGRAM_WEBHOOK_SECRET&&secret&&secret!==env.TELEGRAM_WEBHOOK_SECRET)return new Response('Unauthorized',{status:401}); const body=await request.text(); if(body.length>65536)return new Response('Payload too large',{status:413}); const u=JSON.parse(body) as TelegramUpdate; const m=u.message; if(!m?.text)return Response.json({ok:true}); if(!allowedTelegram(env,m.from?.id)){return Response.json({ok:false,error:'unauthorized'},{status:403});} const reply=async(t:string)=>env.TELEGRAM_BOT_TOKEN?sendTelegramMessage(env.TELEGRAM_BOT_TOKEN,m.chat.id,t):undefined; const [cmd,arg]=m.text.trim().split(/\s+/,2); if(cmd==='/run-health-check'){const t=await runHealthCheck(env,'telegram'); await reply(`Health check started. Task: ${t.id}`);} else if(cmd==='/pause-agent'){await setPaused(env,true,String(m.from?.id)); await reply('Agent paused.');} else if(cmd==='/resume-agent'){await setPaused(env,false,String(m.from?.id)); await reply('Agent resumed.');} else if(cmd==='/approve'){const r=await handleApproval(env,arg,'approve',String(m.from?.id)); await reply(`Approval result: ${JSON.stringify(r)}`);} else if(cmd==='/reject'){const r=await handleApproval(env,arg,'reject',String(m.from?.id)); await reply(`Rejection result: ${JSON.stringify(r)}`);} else if(cmd==='/status'){const s=await getStatus(env); await reply(formatStatus(s));} else if(cmd==='/tasks'){await reply((await listTasks(env)).map((t:any)=>`${t.id} ${t.status} ${t.created_at}`).join('\n')||'No tasks.');} else if(cmd==='/incidents'){await reply((await listIncidents(env)).map((i:any)=>`${i.id} ${i.severity} ${i.status} x${i.occurrence_count} ${i.title}`).join('\n')||'No incidents.');} else if(cmd==='/incident'){const i=await getIncident(env,arg); await reply(i?formatIncident(rowIncident(i)):'Incident not found.');} else if(cmd==='/health'){await reply('Latest health observations are available after running /run-health-check.');} else {await reply('/status /health /tasks /incidents /incident <id> /approve <token> /reject <token> /run-health-check /pause-agent /resume-agent /help');} return Response.json({ok:true});}
function rowIncident(r:any):Incident{return{id:r.id,fingerprint:r.fingerprint,title:r.title,service:r.service,environment:r.environment,severity:r.severity,status:r.status,occurrenceCount:r.occurrence_count,firstSeenAt:r.first_seen_at,lastSeenAt:r.last_seen_at,latestObservationId:r.latest_observation_id,diagnosis:r.diagnosis?JSON.parse(r.diagnosis):undefined,jiraIssueKey:r.jira_issue_key,telegramMessageId:r.telegram_message_id}}
export async function listTasks(env:OpsEnv){return (await env.AGENT_DB.prepare('SELECT * FROM agent_tasks ORDER BY created_at DESC LIMIT 20').all()).results??[]}
export async function listIncidents(env:OpsEnv){return (await env.AGENT_DB.prepare('SELECT * FROM incidents WHERE status IN ("open","acknowledged","jira_pending","jira_created") ORDER BY severity DESC,last_seen_at DESC LIMIT 20').all()).results??[]}
export async function getIncident(env:OpsEnv,id:string){return env.AGENT_DB.prepare('SELECT * FROM incidents WHERE id=?1').bind(id).first()}
export async function getStatus(env:OpsEnv){return {state:await getState(env),activeTasks:(await listTasks(env)).filter((t:any)=>['pending','running','waiting_for_approval'].includes(t.status)).length,openIncidents:(await listIncidents(env)).length,pendingApprovals:((await env.AGENT_DB.prepare('SELECT COUNT(*) c FROM approval_requests WHERE status="pending"').first<any>())?.c??0)}}
export function formatStatus(s:any){return `Agent: ${s.state.paused?'paused':'running'}\nActive tasks: ${s.activeTasks}\nOpen incidents: ${s.openIncidents}\nPending approvals: ${s.pendingApprovals}\nLast success: ${s.state.lastSuccessfulRunAt??'never'}\nLast failure: ${s.state.lastFailedRunAt??'never'}`}
export async function handleInternal(url:URL,request:Request,env:OpsEnv){const auth=request.headers.get('x-admin-token')??request.headers.get('x-internal-secret')??''; if(auth!==(env.INTERNAL_STATUS_SECRET??env.AGENTIC_ADMIN_TOKEN))return Response.json({ok:false,error:'Unauthorized'},{status:401}); if(url.pathname==='/internal/run-health-check'&&request.method==='POST')return Response.json(await runHealthCheck(env,'event')); if(url.pathname==='/internal/status')return Response.json(await getStatus(env)); if(url.pathname==='/internal/tasks')return Response.json(await listTasks(env)); if(url.pathname==='/internal/incidents')return Response.json(await listIncidents(env)); const m=url.pathname.match(/^\/internal\/incidents\/([^/]+)$/); if(m)return Response.json(await getIncident(env,m[1])??{ok:false,error:'not_found'}); const a=url.pathname.match(/^\/internal\/approvals\/([^/]+)\/(approve|reject)$/); if(a&&request.method==='POST')return Response.json(await handleApproval(env,a[1],a[2] as any,'internal')); return undefined}
